# This file was generated by GoReleaser. DO NOT EDIT.
cask "breathe" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_darwin_amd64.tar.gz"
      sha256 "e03805c48aaa8cd58033b6df1955cc4ab2e0eb5ae8d948b46944b9713613689c"
    end
    on_arm do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_darwin_arm64.tar.gz"
      sha256 "09d89e3eb6eafa4f501a6e439ad69f4f5d5e250e4d0b2cea9bfeaed4f5326d35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_linux_amd64.tar.gz"
      sha256 "c26e7469f373c51e2043196301e24831a18d2d4c7edb4bda5ce3bdd53dd9a6b6"
    end
    on_arm do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_linux_arm64.tar.gz"
      sha256 "61794f27b620af1a3b0f29bb09e8275aaa47376629a93f0192e60c50e072ee50"
    end
  end

  name "breathe"
  desc "A Pomodoro timer with physics-based TUI animations."
  homepage "https://github.com/Jaace/breathe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breathe"

  # No zap stanza required

end
