# This file was generated by GoReleaser. DO NOT EDIT.
cask "breathe" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_darwin_amd64.tar.gz"
      sha256 "17df01c9efc3de6bf0433afea2c0e2a31c70e061135ecb32125f8df6f4e7142e"
    end
    on_arm do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_darwin_arm64.tar.gz"
      sha256 "413d24d0b91fb8d997aeadfc5c760813966daae75fbadaac70dd02d05abf28af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_linux_amd64.tar.gz"
      sha256 "e9b5a78b6343543b08fdd07e73f10cf4196c3801e667eab470a181ff1ebb0329"
    end
    on_arm do
      url "https://github.com/Jaace/breathe/releases/download/v#{version}/breathe_#{version}_linux_arm64.tar.gz"
      sha256 "ecba9e9931e58250139a5e045fb590910b36c2f7bb9fb652e10b516ab7aec576"
    end
  end

  name "breathe"
  desc "A Pomodoro timer with physics-based TUI animations."
  homepage "https://github.com/Jaace/breathe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breathe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/breathe"],
                     sudo: false
    end
  end

  # No zap stanza required

end
