# This file was generated by GoReleaser. DO NOT EDIT.
cask "drawer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2fe9b2fd90d5e0faab362de2f84d5c7360928c680d6229ca849c7e8e40394bca"
      url "https://github.com/Jaace/drawer/releases/download/v#{version}/drawer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e253f2edb37780ef51cf919a84edb4be64c849f1cae6bd2b68a176b383a4ea79"
      url "https://github.com/Jaace/drawer/releases/download/v#{version}/drawer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a51c0204ed62b169ae84f251f349cc22e0f5e52387f0f7c3e3c6ab3299b46366"
      url "https://github.com/Jaace/drawer/releases/download/v#{version}/drawer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbaf77d1eac6e56a9b1389049e9e9b78fa135bd82d19559c0ca43a8fef464b79"
      url "https://github.com/Jaace/drawer/releases/download/v#{version}/drawer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drawer"
  desc "The git stash TUI that doesn't suck — preview, prune, and tame your stash drawer."
  homepage "https://github.com/Jaace/drawer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drawer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/drawer"],
                     sudo: false
      system_command "/bin/ln",
                     args: ["-sf", "#{HOMEBREW_PREFIX}/bin/drawer", "#{HOMEBREW_PREFIX}/bin/git-drawer"],
                     sudo: false
    end
  end

  # No zap stanza required

end
